package exception;

public class OneTryMultipleCatch {
	public static void main(String[] args) {
		int i,j=8,k=2;
		int[] array=new int[3];
		try
		{
			i=j/k;
			array[5]=8;
		}
		catch(ArithmeticException e)
		{
			System.out.println("Divided by zero.");
			//e.printStackTrace();
		}
		catch(ArrayIndexOutOfBoundsException e)
		{
			System.out.println("Array out of Bound");
		}
		System.out.println("The value of j:"+j);
	}

}
