package exception;

public class OneTryMultipleCatch {
	public static void main(String[] args) {
		int i,j=8,k=0;
		int[] array=new int[3];
		try
		{
			i=j/k;
			for(i=0;i<5;i++)
			{
				i=i+1;
			}
		}
		catch(ArithmeticException e)
		{
			System.out.println("Divided by zero.");
			//e.printStackTrace();
		}
		System.out.println("The value of j:"+j);
	}

}
